require:
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rails
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'components/**/spec/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'
  TargetRubyVersion: 3.2
  SuggestExtensions: true

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'

RSpec/AnyInstance:
  Enabled: false