name: Rubocop

on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2.4'
      - name: Run rubocop
        run: |
          bundle exec rubocop