name: Sorbet Type Checking
on:
  push:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2.4'

      - name: Install dependencies
        run: bundle install

      - name: Run Sorbet
        run: bundle exec srb tc

